# Install-AutoRefreshRate.ps1
# 安装电源感知自动刷新率切换（离电 60Hz / 插电 165Hz）
# 用法: .\Install-AutoRefreshRate.ps1 [-BatteryHz 60] [-AcHz 165]

param(
    [int]$BatteryHz = 60,
    [int]$AcHz      = 165
)

$ErrorActionPreference = 'Stop'
$taskName    = 'AutoRefreshRate'
$switchScript = Join-Path $PSScriptRoot 'Set-RefreshRate.ps1'
$vbsScript    = Join-Path $PSScriptRoot 'AutoRefreshRate-Trigger.vbs'

# ====== 1. 检查核心脚本 ======
if (-not (Test-Path $switchScript)) {
    Write-Error "找不到 Set-RefreshRate.ps1，请确保它与本脚本在同一目录"
    Read-Host "按 Enter 退出"; exit 1
}

# ====== 2. 生成 VBS 包装器入口 ======
$vbsContent = @"
' AutoRefreshRate-Trigger.vbs
' 无感启动 Set-RefreshRate.ps1（自动模式，根据电源切换刷新率）
' Generated by Install-AutoRefreshRate.ps1 — BatteryHz=$BatteryHz, AcHz=$AcHz

Set fso = CreateObject("Scripting.FileSystemObject")
Set ws  = CreateObject("WScript.Shell")

scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
ps1Path   = scriptDir & "\Set-RefreshRate.ps1"
params    = " -BatteryHz $BatteryHz -AcHz $AcHz"

ws.Run "pwsh -NoProfile -WindowStyle Hidden -File """ & ps1Path & """" & params, 0, True
"@

Set-Content -Path $vbsScript -Value $vbsContent -Encoding ASCII
Write-Host "✓ VBS 包装器已生成: $vbsScript" -ForegroundColor Green

# ====== 3. 清理旧任务 ======
$existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "  卸载旧任务: $taskName" -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
}

# ====== 4. 创建计划任务 ======
$wscriptExe = Join-Path $env:SystemRoot 'System32\wscript.exe'

$action = New-ScheduledTaskAction `
    -Execute $wscriptExe `
    -Argument "`"$vbsScript`""

$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Highest

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries:$true `
    -DontStopIfGoingOnBatteries:$true `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -Compatibility Win8

# 三个触发器: 开机 + 登录 + 每3分钟轮询
$triggers = @()
$triggers += New-ScheduledTaskTrigger -AtStartup
$triggers += New-ScheduledTaskTrigger -AtLogOn
# 无限重复: 3650 天 ≈ 10 年
$triggers += New-ScheduledTaskTrigger -Once -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Minutes 3) `
    -RepetitionDuration (New-TimeSpan -Days 3650)

Register-ScheduledTask -TaskName $taskName `
    -Action $action -Principal $principal -Settings $settings `
    -Trigger $triggers -Force | Out-Null

Write-Host "✓ 计划任务已注册: $taskName" -ForegroundColor Green

# ====== 5. 首次同步 ======
Write-Host ""
Write-Host "  执行首次同步..." -ForegroundColor Cyan
& pwsh -NoProfile -File $switchScript -BatteryHz $BatteryHz -AcHz $AcHz

# ====== 6. 总结 ======
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  安装完成！" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  规则 : 电池 → ${BatteryHz}Hz  /  电源 → ${AcHz}Hz" -ForegroundColor White
Write-Host "  触发 : 开机 + 登录 + 每 3 分钟轮询"              -ForegroundColor White
Write-Host "  入口 : wscript.exe → $vbsScript"                  -ForegroundColor DarkGray
Write-Host ""
Write-Host "  管理:" -ForegroundColor DarkGray
Write-Host "    查看  : Get-ScheduledTask '$taskName'"           -ForegroundColor DarkGray
Write-Host "    运行  : Start-ScheduledTask '$taskName'"         -ForegroundColor DarkGray
Write-Host "    状态  : Get-ScheduledTaskInfo '$taskName'"       -ForegroundColor DarkGray
Write-Host "    卸载  : Unregister-ScheduledTask '$taskName'"    -ForegroundColor DarkGray
Write-Host ""
Read-Host "按 Enter 退出"
