# Install-AutoRefreshRate.ps1
# 安装电源感知自动刷新率切换（事件驱动 + 轮询兜底）
# 用法: .\Install-AutoRefreshRate.ps1 [-BatteryHz 60] [-AcHz 165]


param(
    [int]$BatteryHz = 60,
    [int]$AcHz      = 165

)

# ====== 提权检查 =====
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    $myPath = $MyInvocation.MyCommand.Path
    $myArgs  = $PSBoundParameters.GetEnumerator() | ForEach-Object { "-$($_.Key) $($_.Value)" }
    Start-Process pwsh -Verb RunAs -ArgumentList "-NoProfile -File `"$myPath`" $myArgs"
    exit
}

$ErrorActionPreference = 'Stop'
$taskName       = '离电来电自动刷新率切换'
$taskPath       = '\事件查看器任务\'
$taskFullName   = "${taskPath}${taskName}"
$switchScript   = Join-Path $PSScriptRoot 'Set-RefreshRate.ps1'
$vbsScript      = Join-Path $PSScriptRoot 'AutoRefreshRate-Trigger.vbs'
$userId         = "$env:USERDOMAIN\$env:USERNAME"

# ====== 1. 检查核心脚本 ======
if (-not (Test-Path $switchScript)) {
    Write-Error "找不到 Set-RefreshRate.ps1，请确保它与本脚本在同一目录"
    Read-Host "按 Enter 退出"; exit 1
}

# ====== 2. 生成 VBS 包装器入口 ======
$vbsContent = @"
' AutoRefreshRate-Trigger.vbs
' 无感启动 Set-RefreshRate.ps1（自动模式，根据电源切换刷新率）
' Generated by Install-AutoRefreshRate.ps1 — BatteryHz=$BatteryHz, AcHz=$AcHz

Set fso = CreateObject("Scripting.FileSystemObject")
Set ws  = CreateObject("WScript.Shell")

scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
ps1Path   = scriptDir & "\Set-RefreshRate.ps1"
params    = " -BatteryHz $BatteryHz -AcHz $AcHz"

ws.Run "pwsh -NoProfile -WindowStyle Hidden -File """ & ps1Path & """" & params, 0, True
"@

Set-Content -Path $vbsScript -Value $vbsContent -Encoding ASCII
Write-Host "✓ VBS 包装器已生成: $vbsScript" -ForegroundColor Green

# ====== 3. 清理旧任务 ======
$existing = Get-ScheduledTask -TaskName $taskName -TaskPath $taskPath -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "  卸载旧任务: $taskFullName" -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $taskName -TaskPath $taskPath -Confirm:$false
}

# ====== 4. 构建事件驱动任务 XML ======
# 触发器：
#   - Kernel-Power 105: 接通电源
#   - Kernel-Power 107: 断开电源
#   - SessionUnlock:    解锁会话
#   - At startup:       开机
#   - At logon:         登录（延迟 10s）

$taskXml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>$userId</Author>
    <Description>检测电源状态自动切换显示器刷新率：电池→${BatteryHz}Hz，电源→${AcHz}Hz</Description>
  </RegistrationInfo>
  <Triggers>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='Microsoft-Windows-Kernel-Power'] and EventID=105]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
    </EventTrigger>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='Microsoft-Windows-Kernel-Power'] and EventID=107]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
    </EventTrigger>
    <SessionStateChangeTrigger>
      <Enabled>true</Enabled>
      <StateChange>SessionUnlock</StateChange>
      <UserId>$userId</UserId>
    </SessionStateChangeTrigger>
    <BootTrigger>
      <Enabled>true</Enabled>
    </BootTrigger>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT10S</Delay>
      <UserId>$userId</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$userId</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <AllowStartOnBatteries>true</AllowStartOnBatteries>
    <DontStopIfGoingOnBatteries>true</DontStopIfGoingOnBatteries>
    <StartWhenAvailable>true</StartWhenAvailable>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <Compatibility>Win8</Compatibility>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\Windows\System32\wscript.exe</Command>
      <Arguments>"$vbsScript"</Arguments>
    </Exec>
  </Actions>
</Task>
"@

# ====== 5. 创建事件任务 ======
# 先确保目录存在（schtasks 不支持自动创建，用临时任务创建目录再删）
$folderExists = Get-ScheduledTask -TaskPath $taskPath -ErrorAction SilentlyContinue
if (-not $folderExists) {
    $dummyAction = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument '/c exit'
    $dummyPrincipal = New-ScheduledTaskPrincipal -UserId $userId -LogonType Interactive
    $dummyTask = Register-ScheduledTask -TaskName '_dummy_folder_creator' -TaskPath $taskPath `
        -Action $dummyAction -Principal $dummyPrincipal -Trigger (New-ScheduledTaskTrigger -AtStartup) -Force
    Unregister-ScheduledTask -TaskName '_dummy_folder_creator' -TaskPath $taskPath -Confirm:$false
}

$tempXmlPath = Join-Path $env:TEMP 'AutoRefreshRate_Task.xml'
$taskXml | Out-File -FilePath $tempXmlPath -Encoding Unicode
Register-ScheduledTask -Xml (Get-Content $tempXmlPath -Raw) -TaskName $taskName -TaskPath $taskPath -Force | Out-Null
Remove-Item $tempXmlPath -Force

Write-Host "✓ 事件任务已注册: $taskFullName" -ForegroundColor Green

# ====== 6. 首次同步 ======
Write-Host ""
Write-Host "  执行首次同步..." -ForegroundColor Cyan
& pwsh -NoProfile -File $switchScript -BatteryHz $BatteryHz -AcHz $AcHz

# ====== 7. 总结 ======
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  安装完成！" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  规则 : 电池 → ${BatteryHz}Hz  /  电源 → ${AcHz}Hz" -ForegroundColor White
Write-Host "  触发 : Kernel-Power 105/107 + 解锁 + 开机 + 登录"  -ForegroundColor White
Write-Host "  入口 : wscript.exe → $vbsScript"                  -ForegroundColor DarkGray
Write-Host ""
Write-Host "  管理:" -ForegroundColor DarkGray
Write-Host "    查看  : Get-ScheduledTask -TaskName '$taskName' -TaskPath '$taskPath'"   -ForegroundColor DarkGray
Write-Host "    运行  : Start-ScheduledTask -TaskName '$taskName' -TaskPath '$taskPath'" -ForegroundColor DarkGray
Write-Host "    状态  : Get-ScheduledTaskInfo -TaskName '$taskName' -TaskPath '$taskPath'" -ForegroundColor DarkGray
Write-Host "    卸载  : Unregister-ScheduledTask -TaskName '$taskName' -TaskPath '$taskPath'" -ForegroundColor DarkGray
Write-Host ""
Read-Host "按 Enter 退出"
